### ISSUE TITLE
What about resources taking long time to create

### ISSUE THREAD

**Issue by jbenoit2011** [carlnordenfelt/lulo#1]
I just stumbled upon your project. It really looks great. This is the kind of projects I need when I encounter lack of support from CloudFormation.
This project seems to work great for resources quick to create, but what does happen if a resources takes more time to be created than the Lambda time limit (5 minutes), e.g: RDS database, EB environment, etc ...
Is there a kind of asynchronous process to notify to the CloudFormation stack?

Thank you.

**Comment by carlnordenfelt** [comment]
Hi,

This is not something I've thought of but it should be possible. It would
require some work though and involves not sending the response to cfn
immediately but to listen for an event, or poll regularly for status, and
when the resource is complete, trigger the can response.

**Comment by jbenoit2011** [comment]
Ok. If I come up with a solution, I will reopen this ticket. I close it for the moment.
Thanks.
